Members) grid complete
LikeLionHGU/12th-frontend pull request #60
Opened 2024-01-25 11:55 UTC by LeeHannaa

2024-01-25 12:08 UTC, healim01 approved these changes

2024-01-25 12:08 UTC, healim01 commented on img/이한나.png
사진이 마음에 드네요

2024-01-25 12:08 UTC, healim01 commented on index.html
>          <div class="modal_img">
다음번엔 아이콘을 사용해봐도 좋을거 같아요~!

2024-01-25 12:10 UTC, junglesub requested changes
https://www.loom.com/share/f4a8ce9023c6439eb214e35395b32a6c

보시면 두번째 배너가 나올 때 모달이 없어집니다. 확인해봐야할 것 같습니다

2024-01-25 13:40 UTC, LeeHannaa commented
> https://www.loom.com/share/f4a8ce9023c6439eb214e35395b32a6c
> 
> 보시면 두번째 배너가 나올 때 모달이 없어집니다. 확인해봐야할 것 같습니다

모달의 문제가 아니라 배너 두번째 반응형이 적용이 안되어서 배너때문에 가로 스크롤이 생겨서 그렇게 보입니다! 배너 반응형으로 가로 길이 고정해주면 똑바로 적용된다고 생각합니다! 오류 시 다시 알려주세요!

2024-01-25 13:44 UTC, LeeHannaa commented on index.html
>          <div class="modal_img">
저렇게 보이지만 진하고 작은 엑스 아이콘입니다..ㅎㅎ

2024-01-25 13:46 UTC, junglesub commented
> 모달의 문제가 아니라 배너 두번째 반응형이 적용이 안되어서 배너때문에 가로 스크롤이 생겨서 그렇게 보입니다! 배너 반응형으로 가로 길이 고정해주면 똑바로 적용된다고 생각합니다! 오류 시 다시 알려주세요!

아 확인했습니다. 배너 확인 후에 추가적으로 알려드리도록 하겠습니다.

2024-01-27 05:23 UTC, LeeHannaa commented
#62에서 해결

2024-01-27 05:23 UTC, closed without merging